JeongJaeSoon/e-global-zone_Laravel-project_Project-management

.env, README.md, directoryList.md, package.json, src/App.js, src/app/App.js, src/app/Routes.js, src/components/common/CalendarSmall.js, src/components/common/ReservationList.js, src/components/mobile/Header.js, src/components/mobile/MobileTemplate.js, src/config/color.js, src/config/globalStyles.js, src/config/layout.js, src/index.js, src/redux/loginSlice/loginSlice.js, src/redux/store.js, src/routes/Reservation/Reservation.js, src/routes/Result/Result.js, src/routes/Schedule/Schedule.js, yarn.lock
Components
+ mobile Hedaer, Template
+ CalendarSmall(temp)
+ ReservationList
=> react-router-dom setting & Korean student's reservation page

E_Global_Zone/app/Http/Controllers/ForeignerController.php, E_Global_Zone/app/Http/Controllers/KoreanController.php, E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Http/Controllers/RestrictKoreanController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/app/Student_foreigner.php, E_Global_Zone/app/Student_korean.php, E_Global_Zone/composer.json, E_Global_Zone/composer.lock, E_Global_Zone/config/auth.php, E_Global_Zone/routes/api.php, E_Global_Zone/routes/web.php
- API 라우팅
1. admin
2. foreigner
3. korean
- 컨트롤러
=> API Routing & Controller Setting

E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/composer.json, E_Global_Zone/composer.lock, E_Global_Zone/config/auth.php, E_Global_Zone/database/migrations/2020_08_02_081548_create_student_foreigners_table.php, E_Global_Zone/routes/api.php
전체 스케줄 조회, 개인 스케줄 조회 Req / Res 테스트 완료.
Todo
=> Scheudle - 전체 스케줄 조회, 개인 스케줄 조회

E_Global_Zone/app/Department.php, E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/app/Reservation.php, E_Global_Zone/app/Restricted_student_korean.php, E_Global_Zone/app/Schedule.php, E_Global_Zone/app/Section.php, E_Global_Zone/app/Setting.php, E_Global_Zone/app/Student_foreigner.php, E_Global_Zone/app/Student_foreigners_contact.php, E_Global_Zone/app/Student_korean.php, E_Global_Zone/app/Work_student_foreigner.php, E_Global_Zone/config/auth.php, E_Global_Zone/routes/api.php
- Schedule 
1. 등록
2. 업데이트
3. 삭제
- Reservation 
1.신청 학생 조회
2. 스케줄 신청 학생 명단 승인
3. 스케줄 출석 결과 입력
=> Schedule - 스케줄 등록, 업데이트, 삭제 & Reservation - 신청 학생 조회, 승인, 결과입력

E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/routes/api.php
- Reservation
1. 한국인학생 - 예약 신청
2. 한국인학생 - 내 예약 일정 조회
3. 한국인학생 - 내 예약 일정 삭제
*수정사항
한국인 학생페이지 -> 예약조회 -> 출석 인증 완료 status 결과 반환 값은
결과 관리 페이지로 이동 요청.
=> Reservation - 한국인학생 예약신청, 조회, 삭제

E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/routes/api.php
조인 관계 없이, 무분별한 foreach 사용
-> Refactoring by Eloquent ORM => Join
=> Refactoring by Eloquent ORM => Join

E_Global_Zone/app/Http/Controllers/DepartmentController.php, E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/routes/api.php
1. 등록된 계열 & 학과 조회
2. 계열 & 학과 등록
3. 계열 & 학과 이름 변경
4. 계열 & 학과 삭제
=> Department - CRUD

E_Global_Zone/app/Http/Controllers/ForeignerController.php, E_Global_Zone/app/Http/Controllers/KoreanController.php, E_Global_Zone/app/Student_foreigners_contact.php, E_Global_Zone/app/Work_student_foreigner.php, E_Global_Zone/database/migrations/2020_08_02_081552_create_work_student_foreigners_table.php, E_Global_Zone/routes/api.php
- ### Foreigner Controller
1. 학기별 전체 유학생 정보 조회
2. 특정 유학생 정보 조회
3. 학기별 유학생 등록
4. 학기별 유학생 수정
5. 유학생 계정 생성
6. 유학생 비밀번호 변경
7. 유학생 계정 삭제
=> Foreigner -  CRUD

E_Global_Zone/.idea/workspace.xml, E_Global_Zone/app/Providers/AuthServiceProvider.php, E_Global_Zone/app/SchedulesResultImg.php, E_Global_Zone/database/migrations/2020_08_09_153855_create_schedules_result_imgs_table.php
1. Initial password 저장 방식 변경
- 기존 : column default 값 지정
- 변경 : settings 에 저장된 Hash PW 사용
2. 결과 입력 시, 이미지 저장 테이블 정의
1. 로그아웃 시 revoke
2. 유효기간 1일 후 만료
=> Refactor multi auth

E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/app/Http/Controllers/SettingController.php, E_Global_Zone/app/Setting.php, E_Global_Zone/database/migrations/2020_08_02_081638_create_settings_table.php, E_Global_Zone/routes/api.php
- Schedule  Algorithm
=> 지정된 날짜 제외부분 bug fix.
- SettingController
=> 환경변수 조회, 저장 추가.
=> Bug fix :: Schedule Algorithm & Create :: SettingController

E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/app/Http/Controllers/SettingController.php, E_Global_Zone/app/SchedulesResultImg.php, E_Global_Zone/config/filesystems.php, E_Global_Zone/routes/api.php
<description>
config/filesystem - 이미지 업로드 심볼릭 링크 구성.
model/SchedulesResultImg - fillable 속성에 기본키 추가.
Controller/ReservationController - 출석 사진 저장 알고리즘 구현.
<TODO>
config 파일 :: 서버 아이피 + 포트 관리하기.
=> Reservation :: 출석 결과 입력 이미지 처리

E_Global_Zone/.idea/workspace.xml, E_Global_Zone/app/Http/Controllers/LoginController.php, E_Global_Zone/app/Http/Controllers/RestrictKoreanController.php, E_Global_Zone/app/Http/Controllers/SectionController.php, E_Global_Zone/app/Restricted_student_korean.php, E_Global_Zone/database/migrations/2020_08_02_081547_create_restricted_student_koreans_table.php, E_Global_Zone/routes/api.php
1. 조회, 추가, 수정(상태변경)
2. 학기 유효성 검사
3. migration 제한 시작일 기본일(등록 시점) 지정
=> Student korean restrict

E_Global_Zone/app/Http/Controllers/DepartmentController.php, E_Global_Zone/app/Http/Controllers/ForeignerController.php, E_Global_Zone/app/Http/Controllers/KoreanController.php, E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/app/Work_student_foreigner.php, E_Global_Zone/routes/api.php
<description>
update : routes/api -> 대분류 작업 ( 관리자 / 유학생 / 한국인 학생 ) => 소분류 작업( 기능별 ) 분류 완료.
<todo-list>
KoreanController - 전체 한국인 학생 정보 조회 API  페이지네이션 기능 추가 예정.
=> API 주소 리펙토링

E_Global_Zone/app/Http/Controllers/ForeignerController.php, E_Global_Zone/app/Http/Controllers/KoreanController.php, E_Global_Zone/app/Http/Controllers/LoginController.php, E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/routes/api.php
<description>
bug  : 계정 등록 - 대기 명단 조회 API 조회 수정 완료.
docs : 완료된 TODO-list 제거.
etc  : 환경변수 변경 요소 TODO-list에 추가.
<issue-number>
=> Bug-fix :: 계정 등록 - 대기 명단 조회 수정완료

E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/routes/api.php
<description>
feature : 특정 날짜 유학생 전체 스케줄 조회 API 추가.
docs - 변수명 추가 (스토리보드 기준)
reserved_count => 전체 예약 한국인 인원수,
un_permission_count => 예약 미승인 한국인 인원수.
=> Feature :: 관리자 - 특정 날짜 유학생 전체 스케줄 조회 API

E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/routes/api.php
<description>
update : 환경변수 적용한 예약 신청 시작 기준 종료 날짜 적용.
update : 'sch_res_available' 예약 가능 여부 true / false 로 반환.
<issue-number>
=> Update :: 한국인학생 - 현재 날짜 기준 스케줄 조회 API 

E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/app/Http/Controllers/SchedulesResultImgController.php, E_Global_Zone/app/Http/Controllers/SectionController.php, E_Global_Zone/app/Schedule.php, E_Global_Zone/routes/api.php
Feature :: 한국인학생 - 참석한 학기 목록 조회 API
Update :: 관리자 - 해당 유학생 스케줄 등록 API
=> Refactoring :: API 알고리즘 업데이트

E_Global_Zone/app/Http/Controllers/ForeignerController.php, E_Global_Zone/app/Http/Controllers/LoginController.php, E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/app/Http/Controllers/SectionController.php, E_Global_Zone/app/Http/Controllers/SettingController.php, E_Global_Zone/app/Reservation.php, E_Global_Zone/app/Schedule.php, E_Global_Zone/app/SchedulesResultImg.php
Update :: 벨리데이션, 반환 메시지 수정 
Update :: 관리자 - 해당 날짜 출석 결과 미승인건 조회 API 
Bug-fix :: 환경변수 저장
Bug-fix :: 이미지 처리, 출석 결과 입력
=> Refactoring :: API 버그 패치

E_Global_Zone/app/Http/Controllers/ForeignerController.php, E_Global_Zone/app/Http/Controllers/KoreanController.php, E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Http/Controllers/RestrictKoreanController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/app/Reservation.php, E_Global_Zone/routes/api.php
Feature :: 
1) 관리자 - 해당 스케줄 학생 추가 API 
2) 관리자 - 특정 한국인 학생 정보 조회 API
Update :: 계정 등록 - 승인 API 리펙토링
=> Refactoring :: API 추가

E_Global_Zone/app/Http/Controllers/ForeignerController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/app/Http/Controllers/SectionController.php, E_Global_Zone/app/Setting.php, E_Global_Zone/routes/api.php
Feature :: 관리자 - 해당 학기 미등록 유학생 정보 조회 API 생성.
Bug-fix :: 유학생 계정 생성 벨리데이션, 유학생 정보 누적 수정완료.
=> Refactoring :: API 추가, Bug-fix

E_Global_Zone/app/Console/Kernel.php, E_Global_Zone/app/Http/Controllers/ForeignerController.php, E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Http/Controllers/RestrictKoreanController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/app/Http/Controllers/SectionController.php, E_Global_Zone/app/Schedule.php, E_Global_Zone/app/Setting.php, E_Global_Zone/app/Student_foreigner.php, E_Global_Zone/database/migrations/2020_08_02_081548_create_student_foreigners_table.php, E_Global_Zone/database/migrations/2020_08_02_081550_create_schedules_table.php, E_Global_Zone/routes/api.php
Update :: DB Schema, 즐겨찾기 API, 예약신청 정원 확인.
Feature :: Kernel - 예약 미승인 횟수 자동 카운팅.
=> Refactoring :: 예약 미승인 횟수 자동 카운팅, DB 스키마 수정

E_Global_Zone/app/Console/Kernel.php, E_Global_Zone/app/Http/Controllers/ForeignerController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/app/Schedule.php
Update :: 관리자 - 특정 날짜 전체 유학생 스케줄 조회 API
Bug-fix :: 환경변수 사용 조건 추가
=> Refactoring :: 관리자 - 전체 유학생 스케줄 조회 리펙토링 & Bug-fix

E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php
=> [0.1.0] Bug-fix :: Validation, Sql err

E_Global_Zone/app/Http/Controllers/KoreanController.php, E_Global_Zone/app/Http/Controllers/RestrictKoreanController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/app/Restricted_student_korean.php, E_Global_Zone/routes/api.php
<description>
update : Restricted_student_korean Model 최근 이용 제한 정보 조회 함수 등록.
한국인학생 이용제한 등록 알고리즘 수정.
<issue-number>
=> [0.2.2] Update :: 제한 학생 관련 API

E_Global_Zone/app/Http/Controllers/RestrictKoreanController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/app/Restricted_student_korean.php
Feature : 출석결과 - 한국인 학생 결석 자동 카운팅 알고리즘.
Bug-fix :: spell-check.
=> [0.3.0] Feature : 출석결과 - 한국인 학생 결석 자동 카운팅 알고리즘

E_Global_Zone/app/Http/Controllers/ForeignerController.php, E_Global_Zone/routes/api.php
=> [0.3.1] Update :: 비밀번호 변경 API

E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/app/Http/Controllers/SectionController.php, E_Global_Zone/app/Setting.php, E_Global_Zone/routes/api.php
=> [0.3.2] Update :: 관리자, 유학생, 한국인학생 미들웨어 적용

E_Global_Zone/app/Http/Controllers/ForeignerController.php, E_Global_Zone/app/Http/Controllers/KoreanController.php, E_Global_Zone/app/Http/Controllers/LoginController.php, E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/app/Http/Controllers/SectionController.php, E_Global_Zone/app/Http/Middleware/GoogleAuth.php, E_Global_Zone/routes/api.php
[0.3.3] Update :: 한국인학생 로그인 / 회원가입 API
[0.3.4] Feature :: 관리자 - 유학생 개인 스케줄 추가 API
=> [0.3.5] Feature :: 관리자 - 유학생 개인 스케줄 추가 API

E_Global_Zone/app/Http/Controllers/ForeignerController.php, E_Global_Zone/app/Http/Controllers/KoreanController.php, E_Global_Zone/app/Http/Controllers/LoginController.php, E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Http/Controllers/SectionController.php, E_Global_Zone/routes/api.php
=> [0.3.6] Bug-fix :: small bug

E_Global_Zone/app/Http/Controllers/ForeignerController.php, E_Global_Zone/app/Http/Controllers/KoreanController.php, E_Global_Zone/app/Http/Controllers/LoginController.php, E_Global_Zone/app/Http/Controllers/RestrictKoreanController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/app/Http/Controllers/SectionController.php, E_Global_Zone/app/Http/Controllers/SettingController.php
Update :: 전체 한국인 학생 정보 조회 orderby
Bug-fix :: 환경변수 저장 input err
=> [0.3.9] Bug-fix :: 환경변수 저장 input err

E_Global_Zone/app/Http/Controllers/ForeignerController.php, E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/app/Restricted_student_korean.php
=> [0.3.91] Bug-fix :: 유학생 비밀번호 초기화, 예약 명단 승인

E_Global_Zone/app/Http/Controllers/KoreanController.php, E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/app/Http/Controllers/SectionController.php, E_Global_Zone/app/SchedulesResultImg.php
update : 이미지 처리 변경 완료.
feature : 한국인 학생 - 해당 요일 기준 진행중인 예약 조회 API.
=> [0.4.0] Feature :: image to base64 & 해당 요일 기준 진행중인 예약 조회

E_Global_Zone/app/Http/Controllers/KoreanController.php, E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/app/Http/Controllers/SectionController.php, E_Global_Zone/app/SchedulesResultImg.php
update : 이미지 처리 변경 완료.
feature : 한국인 학생 - 현재 날짜 기준 진행중인 예약 조회 API.
=> [0.5.1] Feature :: image to base64 & 현재 날짜 기준 진행중인 예약 조회

E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/app/SchedulesResultImg.php
bug-fix 👍 
1. 관리자 - 해당 유학생 스케줄 등록 
=> 초기 스케줄 등록간에 현재 날짜가 학기 시작일을 넘겼을때 중복 입력 막기.
2. convert image to base64 err
=> [0.5.2] Bug-fix :: convert image to base64 err

E_Global_Zone/app/Http/Controllers/KoreanController.php, E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Reservation.php
<description>
update :
1. 한국인학생 - 예약 취소 => 환경변수 예약 취소 가능일자 반영.
2. 한국인학생 - 예약 신청 => 동시간대 예약등록 여부 반환.
<issue-number>
=> [0.6.0] Update :: Reservation Controller 리펙토링

E_Global_Zone/app/Http/Controllers/SectionController.php, E_Global_Zone/app/Http/Controllers/SettingController.php
<description>
bug : required_if -> required_with 변경.
=> [0.6.1] Bug-fix :: 학기수정, 환경변수 저장 Validation err

E_Global_Zone/app/Http/Controllers/ForeignerController.php, E_Global_Zone/app/Http/Controllers/KoreanController.php, E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/app/Http/Controllers/SettingController.php, E_Global_Zone/app/Http/Middleware/GoogleAuth.php, E_Global_Zone/app/Providers/AppServiceProvider.php, E_Global_Zone/app/Reservation.php, E_Global_Zone/app/Student_korean.php, E_Global_Zone/database/migrations/2020_08_02_081544_create_sections_table.php, E_Global_Zone/database/migrations/2020_08_02_081547_create_restricted_student_koreans_table.php, E_Global_Zone/database/migrations/2020_08_02_081549_create_student_foreigners_contacts_table.php, E_Global_Zone/database/migrations/2020_08_02_081551_create_reservations_table.php, E_Global_Zone/database/migrations/2020_08_02_081552_create_work_student_foreigners_table.php, E_Global_Zone/database/migrations/2020_08_09_153855_create_schedules_result_imgs_table.php, E_Global_Zone/resources/lang/en/validation.php, E_Global_Zone/routes/api.php
1. 해당 날짜 기준 진행중인 예약 조회 API 반영.
2. database - onDelete('cascade') 속성 추가.
3. custom_validation, db schema type change.
<issue-number>
유학생 계정 생성 -> :in 속성 test 필수.
=> [0.6.2] Update :: api, custom_validation, db schema (type, property)

E_Global_Zone/app/Http/Controllers/ForeignerController.php, E_Global_Zone/app/Http/Controllers/SectionController.php, E_Global_Zone/database/migrations/2020_08_02_081550_create_schedules_table.php, E_Global_Zone/database/migrations/2020_08_02_081551_create_reservations_table.php, E_Global_Zone/database/migrations/2020_08_02_081552_create_work_student_foreigners_table.php
=> [0.6.3] Bug-fix :: onDelete 속성 변경

E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/app/Http/Controllers/WorkStudentForeignerController.php, E_Global_Zone/routes/api.php
<description>
update : 기존 해당 날짜 출석 결과 미승인건 조회 API
-> 'sch_state_of_permission'로 (승인 / 미승인) 조회 API 로 변경.
<issue-number>
=> [0.6.3] Hot-fix :: 관리자 - 해당 날짜 출석 결과 조회 API

E_Global_Zone/app/Console/Kernel.php, E_Global_Zone/app/Http/Controllers/ForeignerController.php, E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/app/Reservation.php, E_Global_Zone/database/migrations/2020_08_02_081545_create_student_koreans_table.php, E_Global_Zone/database/migrations/2020_08_02_081547_create_restricted_student_koreans_table.php, E_Global_Zone/database/migrations/2020_08_02_081548_create_student_foreigners_table.php, E_Global_Zone/database/migrations/2020_08_02_081549_create_student_foreigners_contacts_table.php, E_Global_Zone/database/migrations/2020_08_02_081550_create_schedules_table.php, E_Global_Zone/database/migrations/2020_08_02_081552_create_work_student_foreigners_table.php, E_Global_Zone/routes/api.php
=> [7.0.0] Feature :: 한국인 학생 해당 학기 랭킹(백분율) 조회 API

E_Global_Zone/app/Http/Controllers/ReservationController.php
=> [0.7.0] Hot-fix :: 스케줄 삭제, 예약삭제 API

E_Global_Zone/app/Http/Controllers/ForeignerController.php
=> [0.7.1] hot-fix :: 유학생 정보 변경 API

E_Global_Zone/app/Reservation.php
=> [0.8.0] hot-fix :: whereDate 오류 수정

E_Global_Zone/app/Console/Kernel.php, E_Global_Zone/app/Http/Controllers/SettingController.php, E_Global_Zone/resources/lang/en/validation.php
=> hot-fix :: Kernel 에러 수정

E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/resources/lang/en/validation.php
=> [0.8.1] hot-fix :: 이미지 사이즈 제한

E_Global_Zone/app/Http/Controllers/Controller.php, E_Global_Zone/app/Http/Controllers/ForeignerController.php, E_Global_Zone/app/Http/Controllers/LoginController.php, E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/app/Http/Controllers/SchedulesResultImgController.php, E_Global_Zone/app/Http/Controllers/SettingController.php, E_Global_Zone/app/Reservation.php, E_Global_Zone/app/Schedule.php, E_Global_Zone/app/SchedulesResultImg.php, E_Global_Zone/routes/api.php
=> Update :: 글로벌존 정보 초기화 API & 다국어 관련 코드 수정완료

E_Global_Zone/app/Http/Controllers/Controller.php, E_Global_Zone/app/Http/Controllers/ForeignerController.php, E_Global_Zone/app/Http/Controllers/LoginController.php, E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/app/Http/Controllers/SchedulesResultImgController.php, E_Global_Zone/app/Http/Controllers/SettingController.php, E_Global_Zone/app/Reservation.php, E_Global_Zone/app/Schedule.php, E_Global_Zone/app/SchedulesResultImg.php, E_Global_Zone/routes/api.php
=> Feature :: 글로벌 센터 기준 시간 변경

E_Global_Zone/app/Http/Controllers/Controller.php, E_Global_Zone/app/Http/Controllers/LoginController.php, E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/app/Http/Controllers/SchedulesResultImgController.php, E_Global_Zone/app/Schedule.php, E_Global_Zone/app/SchedulesResultImg.php
=> (G_Center) Update :: 누락된 커밋내역 수정

E_Global_Zone/app/Admin.php, E_Global_Zone/app/Http/Controllers/DataExportController.php, E_Global_Zone/app/Http/Controllers/ScheduleController.php, E_Global_Zone/app/Http/Middleware/AuthenticateMulti.php, E_Global_Zone/app/Student_foreigner.php, E_Global_Zone/config/constants.php, E_Global_Zone/routes/api.php
=> Update :: 누락된 커밋내역 수정

E_Global_Zone/app/Http/Controllers/Controller.php, E_Global_Zone/app/Http/Controllers/LoginController.php, E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Http/Controllers/SchedulesResultImgController.php
Hot-fix :: 다국어 패치 생성자 버그 수정 완료.
=> Hot-fix :: 다국어 패치 생성자 버그 수정

E_Global_Zone/app/Http/Controllers/Controller.php, E_Global_Zone/app/Http/Controllers/LoginController.php, E_Global_Zone/app/Http/Controllers/ReservationController.php, E_Global_Zone/app/Http/Controllers/SchedulesResultImgController.php
[ ZONE ] Hot-fix :: 다국어 패치 생성자 버그 수정 완료.
=> [ ZONE ] Hot-fix :: 다국어 패치 생성자 버그 수정
